version: "3.1"
services:
  web:
    image: common-laravel
    ports:
        - "8181:8181"
    volumes:
        - "./:/app"
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
volumes:
    db_data:   

  